ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMS_Data_Access.HMSModels;
using Microsoft.AspNetCore.Authorization;

namespace Hotel_Management_System.Controllers
{
    [Authorize(Roles="Owner,Receptionist")]
    public class BillsController : Controller
    {
        
        private readonly HotelManagementSystemContext _context;

        public BillsController(HotelManagementSystemContext context)
        {
            _context = context;
        }
        public IActionResult Home()
        {
            return View();
        }
        // GET: Bills
        public async Task<IActionResult> Index()
        {
            var hotelManagementSystemContext = _context.Bill.Include(b => b.Guest).Include(b => b.Service);
            return View(await hotelManagementSystemContext.ToListAsync());
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b => b.Guest)
                .Include(b => b.Service)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // GET: Bills/Create
        public IActionResult Create()
        {
            ViewData["GuestId"] = new SelectList(_context.GuestDetails, "GuestId", "GuestId");
            ViewData["ServiceId"] = new SelectList(_context.Services, "ServiceId", "ServiceId");
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillId,GuestId,Taxes,IssueDate,ServiceId,Unit,CreditCardDetails,Price")] Bill bill, [Bind("Price")]Bill p)
        {
            if (ModelState.IsValid)
            {

                var nights = _context.Reservation.Where(b => b.GuestId==bill.GuestId).Select(s=>s.NumberOfNights).Single(); 
                var nightprice1 = _context.Rates.Select(s =>s.FirstNightPrice).FirstOrDefault();
                var nightprice2 = _context.Rates.Select(s => s.ExtensionPrice).FirstOrDefault();
                var serviceprice = _context.Services.Where(s=>s.ServiceId==bill.ServiceId).Select(s=>s.ServicePrice).Single();
                var price = ((1*nightprice1)+((nights)*nightprice2)+(serviceprice*bill.Unit)) ;

                _context.Add(new Bill
                {
                    BillId=bill.BillId,
                    GuestId=bill.GuestId,
                    Taxes=bill.Taxes,
                    IssueDate=bill.IssueDate,
                    ServiceId=bill.ServiceId,
                    Unit=bill.Unit,
                    CreditCardDetails=bill.CreditCardDetails,
                    Price=(decimal)price
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GuestId"] = new SelectList(_context.GuestDetails, "GuestId", "GuestId", bill.GuestId);
            ViewData["ServiceId"] = new SelectList(_context.Services, "ServiceId", "ServiceId", bill.ServiceId);
            
            return View(bill);
        }

        // GET: Bills/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            ViewData["GuestId"] = new SelectList(_context.GuestDetails, "GuestId", "GuestId", bill.GuestId);
            ViewData["ServiceId"] = new SelectList(_context.Services, "ServiceId", "ServiceId", bill.ServiceId);
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BillId,GuestId,Taxes,IssueDate,ServiceId,Unit,CreditCardDetails,Price")] Bill bill)
        {
            if (id != bill.BillId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillExists(bill.BillId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GuestId"] = new SelectList(_context.GuestDetails, "GuestId", "GuestId", bill.GuestId);
            ViewData["ServiceId"] = new SelectList(_context.Services, "ServiceId", "ServiceId", bill.ServiceId);
            return View(bill);
        }

        // GET: Bills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b => b.Guest)
                .Include(b => b.Service)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bill = await _context.Bill.FindAsync(id);
            _context.Bill.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillExists(int id)
        {
            return _context.Bill.Any(e => e.BillId == id);
        }
    }
}

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Controllers/HomeController.cs
using Hotel_Management_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_Management_System.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Management_System.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Manager")]
        public IActionResult ManagerIndex()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Receptionist")]
        public IActionResult ReceptionistIndex()
        {
            return View();
        }

    }
}

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/Bills/Create.cshtml
@model HMS_Data_Access.HMSModels.Bill

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<h1>Create</h1>

<h4>Bill</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillId" class="control-label"></label>
                <input asp-for="BillId" class="form-control" />
                <span asp-validation-for="BillId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuestId" class="control-label"></label>
                <select asp-for="GuestId" class ="form-control" asp-items="ViewBag.GuestId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Taxes" class="control-label"></label>
                <input asp-for="Taxes" class="form-control" />
                <span asp-validation-for="Taxes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueDate" class="control-label"></label>
                <input asp-for="IssueDate" class="form-control" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <select asp-for="ServiceId" class ="form-control" asp-items="ViewBag.ServiceId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditCardDetails" class="control-label"></label>
                <input asp-for="CreditCardDetails" class="form-control" />
                <span asp-validation-for="CreditCardDetails" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/Bills/Delete.cshtml
@model HMS_Data_Access.HMSModels.Bill

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bill</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Taxes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Taxes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditCardDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditCardDetails)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guest.GuestId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Service.ServiceId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BillId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
    </form>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/Bills/Details.cshtml
@model HMS_Data_Access.HMSModels.Bill

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Bill</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Taxes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Taxes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditCardDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditCardDetails)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guest.GuestId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Service.ServiceId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BillId">Edit</a> |
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/Bills/Edit.cshtml
@model HMS_Data_Access.HMSModels.Bill

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Bill</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BillId" />
            <div class="form-group">
                <label asp-for="GuestId" class="control-label"></label>
                <select asp-for="GuestId" class="form-control" asp-items="ViewBag.GuestId"></select>
                <span asp-validation-for="GuestId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Taxes" class="control-label"></label>
                <input asp-for="Taxes" class="form-control" />
                <span asp-validation-for="Taxes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueDate" class="control-label"></label>
                <input asp-for="IssueDate" class="form-control" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <select asp-for="ServiceId" class="form-control" asp-items="ViewBag.ServiceId"></select>
                <span asp-validation-for="ServiceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditCardDetails" class="control-label"></label>
                <input asp-for="CreditCardDetails" class="form-control" />
                <span asp-validation-for="CreditCardDetails" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/Bills/Home.cshtml
<h1>BILLS</h1>
<ul>
    <li><a asp-action="Index"asp-controller="Bills">Invoices</a></li>
    <li><a asp-action="Create" asp-controller="Bills">Create a Bill</a></li>
    <li><a asp-action="Index" asp-controller="Role">HMS Home Page</a></li>
    <li><a asp-action="ManagerIndex" asp-controller="Role">HMS ManagerHome Page</a></li>
    <li><a asp-action="ReceptionistIndex" asp-controller="Role">HMS ReceptionistHome Page</a></li>
</ul>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/Bills/Index.cshtml
@model IEnumerable<HMS_Data_Access.HMSModels.Bill>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Taxes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IssueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditCardDetails)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Service.ServiceName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Taxes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditCardDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guest.GuestId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Service.ServiceName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BillId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BillId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BillId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index" asp-controller="Role">HMS Home Page</a>