ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Controllers/HomeController.cs
using Hotel_Management_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_Management_System.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Management_System.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Manager")]
        public IActionResult ManagerIndex()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Receptionist")]
        public IActionResult ReceptionistIndex()
        {
            return View();
        }

    }
}

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Controllers/RoomDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMS_Data_Access.HMSModels;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Hotel_Management_System.Controllers
{
    [Authorize(Roles = "Owner,Manager,Receptionist")]
    public class RoomDetailsController : Controller
    {
        private readonly HotelManagementSystemContext _context;

        public RoomDetailsController(HotelManagementSystemContext context)
        {
            _context = context;
        }
        public IActionResult Home()
        {
            return      View();
        }

        // GET: RoomDetails
        public async Task<IActionResult> Index()
        {
            var hotelManagementSystemContext = _context.RoomDetails.Include(r => r.Reservation).Include(r => r.Room);
            return View(await hotelManagementSystemContext.ToListAsync());
        }

        // GET: RoomDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomDetails = await _context.RoomDetails
                .Include(r => r.Reservation)
                .Include(r => r.Room)
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (roomDetails == null)
            {
                return NotFound();
            }

            return View(roomDetails);
        }

        // GET: RoomDetails/Create
        public IActionResult Create()
        {
            ViewData["ReservationId"] = new SelectList(_context.Reservation, "ReservationId", "ReservationId");
            ViewData["RoomId"] = new SelectList(_context.Services, "ServiceId", "ServiceId");
            return View();
        }

        // POST: RoomDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoomId,ReservationId,CheckIn,CheckOut,Period,ServiceId")] RoomDetails roomDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roomDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReservationId"] = new SelectList(_context.Reservation, "ReservationId", "ReservationId", roomDetails.ReservationId);
            ViewData["RoomId"] = new SelectList(_context.Services, "ServiceId", "ServiceId", roomDetails.RoomId);
            return View(roomDetails);
        }

        // GET: RoomDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomDetails = await _context.RoomDetails.FindAsync(id);
            if (roomDetails == null)
            {
                return NotFound();
            }
            ViewData["ReservationId"] = new SelectList(_context.Reservation, "ReservationId", "ReservationId", roomDetails.ReservationId);
            ViewData["RoomId"] = new SelectList(_context.Services, "ServiceId", "ServiceId", roomDetails.RoomId);
            return View(roomDetails);
        }

        // POST: RoomDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoomId,ReservationId,CheckIn,CheckOut,Period,ServiceId")] RoomDetails roomDetails)
        {
            if (id != roomDetails.RoomId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roomDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomDetailsExists(roomDetails.RoomId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReservationId"] = new SelectList(_context.Reservation, "ReservationId", "ReservationId", roomDetails.ReservationId);
            ViewData["RoomId"] = new SelectList(_context.Services, "ServiceId", "ServiceId", roomDetails.RoomId);
            return View(roomDetails);
        }

        // GET: RoomDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomDetails = await _context.RoomDetails
                .Include(r => r.Reservation)
                .Include(r => r.Room)
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (roomDetails == null)
            {
                return NotFound();
            }

            return View(roomDetails);
        }

        // POST: RoomDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roomDetails = await _context.RoomDetails.FindAsync(id);
            _context.RoomDetails.Remove(roomDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomDetailsExists(int id)
        {
            return _context.RoomDetails.Any(e => e.RoomId == id);
        }
    }
}

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/RoomDetails/Create.cshtml
@model HMS_Data_Access.HMSModels.RoomDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>RoomDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <input asp-for="RoomId" class="form-control" />
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationId" class="control-label"></label>
                <select asp-for="ReservationId" class ="form-control" asp-items="ViewBag.ReservationId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CheckIn" class="control-label"></label>
                <input asp-for="CheckIn" class="form-control" />
                <span asp-validation-for="CheckIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckOut" class="control-label"></label>
                <input asp-for="CheckOut" class="form-control" />
                <span asp-validation-for="CheckOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Period" class="control-label"></label>
                <input asp-for="Period" class="form-control" />
                <span asp-validation-for="Period" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <input asp-for="ServiceId" class="form-control" />
                <span asp-validation-for="ServiceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/RoomDetails/Delete.cshtml
@model HMS_Data_Access.HMSModels.RoomDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RoomDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckOut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Period)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Period)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reservation.ReservationId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.ServiceId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoomId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
    </form>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/RoomDetails/Details.cshtml
@model HMS_Data_Access.HMSModels.RoomDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>RoomDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckOut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Period)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Period)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reservation.ReservationId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.ServiceId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RoomId">Edit</a> |
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/RoomDetails/Edit.cshtml
@model HMS_Data_Access.HMSModels.RoomDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>RoomDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoomId" />
            <div class="form-group">
                <label asp-for="ReservationId" class="control-label"></label>
                <select asp-for="ReservationId" class="form-control" asp-items="ViewBag.ReservationId"></select>
                <span asp-validation-for="ReservationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckIn" class="control-label"></label>
                <input asp-for="CheckIn" class="form-control" />
                <span asp-validation-for="CheckIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckOut" class="control-label"></label>
                <input asp-for="CheckOut" class="form-control" />
                <span asp-validation-for="CheckOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Period" class="control-label"></label>
                <input asp-for="Period" class="form-control" />
                <span asp-validation-for="Period" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <input asp-for="ServiceId" class="form-control" />
                <span asp-validation-for="ServiceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/RoomDetails/Home.cshtml
<h1>Room Details</h1>
<ul>
    <li><a asp-action="Index" asp-controller="RoomDetails">Room Details</a></li>
    <li><a asp-action="Create" asp-controller="RoomDetails">Add a Room Details</a></li>
    <li><a asp-action="Index" asp-controller="Role">HMS Home Page</a></li>
    <li><a asp-action="ManagerIndex" asp-controller="Role">HMS ManagerHome Page</a></li>
    <li><a asp-action="ReceptionistIndex" asp-controller="Role">HMS ReceptionistHome Page</a></li>
</ul>

ASP.NET Core Assignments/Hotel Management System/Hotel Management System/Views/RoomDetails/Index.cshtml
@model IEnumerable<HMS_Data_Access.HMSModels.RoomDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CheckIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Period)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reservation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckOut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Period)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reservation.ReservationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.ServiceId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RoomId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RoomId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RoomId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index" asp-controller="Role">HMS Home Page</a>